### ISSUE TITLE
Elastic 5.0 support 

### ISSUE THREAD

**Issue by mkscala** [sadsfae/ansible-elk#16]
Does this support the Elastic 5.0 new stack ?

**Comment by cloudanddevsecops** [comment]
I have the same question, looking forward to the answer.

**Comment by sadsfae** [comment]
Thanks for filing this, I haven't tested this yet with Kibana 5.x - I will do so and report back here, hopefully with a commit.

**Comment by mkscala** [comment]
Any timeline for the Ansible Playbook? I have tested the Docker Compose version for Elastic 5.0.I can share if needed.

**Comment by sadsfae** [comment]
I took a stab at this today, had no issues with 5.1 ES and Kibana but Logstash doesn't seem to be working correctly.  5.1 LS was released recently and their Github [may have some related issues.](https://github.com/elastic/logstash/issues).  My issues were around logstash not fully starting, nothing in log messages with debug turned on and the beats filter not seeming to full start/listen.

I haven't had time to fully investigate why.

Bin directories and paths have changed in the shipped logstash RPM repositories, something to note as well:

```/opt/logstash/bin/logstash```
Has changed to:
```/usr/share/logstash/bin/logstash```

I could be missing something in the filter configurations in ```install/roles/logstash/files/``` but I've checked all the changes in 5.x.  Overall the performance was noticably worse here, and I needed > 2G of memory in my testing VMs which wasn't an issue in the older versions.

I'll look at this again after the Holidays, there are a few existing open issues which may be related with the current version of logstash that may need to be fixed first or I simple could be missing something in the filter configurations that keep LS from binding on TCP/5044 for beats.

If anyone has some working 5.1.x filter configurations for the following files so I can compare that would help me verify it's not the filters.

https://github.com/sadsfae/ansible-elk/blob/master/install/roles/logstash/files/01-lumberjack-input.conf
https://github.com/sadsfae/ansible-elk/blob/master/install/roles/logstash/files/10-syslog-filter.conf
https://github.com/sadsfae/ansible-elk/blob/master/install/roles/logstash/files/10-syslog.conf
https://github.com/sadsfae/ansible-elk/blob/master/install/roles/logstash/files/30-elasticsearch-output.conf
https://github.com/sadsfae/ansible-elk/blob/master/install/roles/logstash/files/30-lumberjack-output.conf

**Comment by kaneda-fr** [comment]
Good to see you are starting working on 5.1 ;)

I have 5.1 deployed manually and working fine I was planning to do  ansible part over the next couple of days.

I'm only working with beats for now and the config file I created is:

input {
  beats {
    port => 5044
    ssl => true
    ssl_certificate => "/etc/pki/tls/certs/logstash-forwarder.crt"
    ssl_key => "/etc/pki/tls/private/logstash-forwarder.key"
  }
}

output {
  elasticsearch {
    hosts => "x.x.x.x:9200"
    manage_template => false
    index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
    document_type => "%{[@metadata][type]}"
  }
}

As soon as I'm done with my end to end deployment I'll look into importing syslog and netflow data.

Are there any modifications you made to make it work with  5.x you can share ?

**Comment by sadsfae** [comment]
That's great @kaneda-fr.  I made no modifications besides the following:

- Update repositories to the latest 5.1
- Update the logstash binary where it's referenced to seed ES initially with local data here:

https://github.com/sadsfae/ansible-elk/blob/master/install/roles/kibana/tasks/main.yml#L25

It looks like our beats config is mostly the same so that doesn't seem to be an issue.  [Testing things manually](https://www.elastic.co/guide/en/logstash/current/config-examples.html#_processing_syslog_messages) with a simple syslog filter it doesn't get to the point of listening on TCP.

```
/usr/share/logstash/bin/logstash -f 10-syslog-filter.conf
```

I need to debug further to see what's happening, I have debug logging turned on but the farthest it gets is:

```
[2016-12-21T08:03:18,837][DEBUG][logstash.runner          ] slowlog.threshold.debug: -1
[2016-12-21T08:03:18,838][DEBUG][logstash.runner          ] slowlog.threshold.trace: -1
[2016-12-21T08:03:18,838][DEBUG][logstash.runner          ] path.queue: "/usr/share/logstash/data/queue"
[2016-12-21T08:03:18,838][DEBUG][logstash.runner          ] *path.settings: "/etc/logstash" (default: "/usr/share/logstash/config")
[2016-12-21T08:03:18,838][DEBUG][logstash.runner          ] *path.logs: "/var/log/logstash/" (default: "/usr/share/logstash/logs")
[2016-12-21T08:03:18,838][DEBUG][logstash.runner          ] --------------- Logstash Settings -------------------
```

strace tells me:

```
pid  1530] futex(0x7fc2600c4354, FUTEX_WAIT_BITSET_PRIVATE, 1, {1148, 933103084}, ffffffff <unfinished ...>
[pid  1539] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid  1539] futex(0x7fc260120f28, FUTEX_WAKE_PRIVATE, 1) = 0
[pid  1539] futex(0x7fc260120f54, FUTEX_WAIT_BITSET_PRIVATE, 1, {1147, 985286561}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
```

I found a reference to a closed issue from 2015 about this, but nothing more yet:

https://github.com/elastic/logstash/issues/2672
https://github.com/logstash-plugins/logstash-input-lumberjack/issues/19

This may also be an [OS/Kernel issue](http://stackoverflow.com/questions/32262946/java-periodically-hangs-at-futex-and-very-low-io-output) and I'm [looking for a fix](https://groups.google.com/d/msg/mechanical-sympathy/QbmpZxp6C64/nMhNjQPTeLEJ).

**Comment by kaneda-fr** [comment]
ok thanks.
I can share my *beat config if that can help.

**Comment by kaneda-fr** [comment]
ok Thanks,

I can share my beat config if you need.
Testing syslog is next on my list, I'll let you know how this goes.

**Comment by mkscala** [comment]
These 2 below links has good infor on filebeat and logstash.
 I wanted to use Filebeat->Elastic-Kibnan, since logstash is for heavy transformation. I don't have much transformation so trying Filebeat. I will test your Elastic 5.0 Ansible this week

https://www.elastic.co/blog/structured-logging-filebeat
https://fauie.com/2016/02/02/installing-filebeat-to-ship-data-to-elasticsearch/

**Comment by mkscala** [comment]
@kaneda-fr, hi did you use Filebeat->Logstash->Elastic-Kibana ?
or Filebeat->Elastic-Kibnan ?

I wanted to just index a json file into Elastic using Filebeat to Elastic, will the below yml work ?
 more filebeat.yml
filebeat.prospectors:
- input_type: log
  paths: ["/home/data/test.json"]
  json.message_key: event
  json.keys_under_root: true

output.elasticsearch:
  hosts: ["xxxxxxxx:9200"]
  template.name: filebeat
  template.path: filebeat.template.json

**Comment by kaneda-fr** [comment]
@mkscala, I'm using Logstash and  going from filebeat straight into elastic works too.

**Comment by mkscala** [comment]
@sadsfae , any luck on anisble roles for elastic 5  & greater version

**Comment by sadsfae** [comment]
@mkscala I've worked on this for a good few hours yesterday and today, something is still wrong with ```logstash 5.2.1``` beats plugin, either via the way it's being deployed or some other aspect of how SSL/TLS verification is done now.  I'm still working on it.  I can get everything working/listening with the following issues:

- very very slow startup time, around 3-5minutes or more
- ~~beats plugin gets kicked out for syntax issues (using same ones we used in 2.x)~~
- SSL support isn't working now with filebeat, still debugging this, not using SSL everything works.

```
ERR Connecting error publishing events (retrying): remote error: tls: handshake failure
```

I know that we can go straight from filebeat --> elasticsearch but that requires listening externally on TCP/9200 which by default has no real authentication solution so I'd much prefer to ship something that uses the standard filebeat -> logstash -> elasticsearch with SSL both for security reasons and to have logstash plugins and friends parse and digest things as it should.

I've opened [an elastic discussion thread](https://discuss.elastic.co/t/ssl-for-filebeat-logstash-remote-error-tls-handshake-failure/75371) about this issue and will follow up with a Github issue it's warranted.

**Comment by sadsfae** [comment]
Update here, I have this all working now manually, I was missing some directives in ```filebeat.yml``` but it's all fine now.  I am still concerned about the slow startup time with ```logstash-5.2.1``` however but it could just be my testing VMs.  I will most likely push a 2.4 series branch of this playbook for folks who still want 2.4 support as it works well, and the changes required to go to ELK/EFK 5.2.1 are very large.

More to come, I will start working on getting this Ansible-deployed fully now.  There are a couple of other fixes that need to be bundled in as well as a new method to populate the ES index.
