### ISSUE TITLE
ansible-galaxy compatibility

### ISSUE THREAD

**Issue by lakshmi-kannan** [sadsfae/ansible-elk#20]
I added your role to requirements.yml and tried to install the role via galaxy but the repo is not galaxy compatible. Specifically, it's missing a meta/main.yml file. A sample is here: https://github.com/geerlingguy/ansible-role-ntp/blob/master/meta/main.yml. 

```
# Role to setup ELK stack on a server (CentOS/RHEL only)
- src: https://github.com/sadsfae/ansible-elk
  name: ansible-elk
  version: master
```

I can open a PR. Just let me know if this is something you are willing to consider.

**Comment by sadsfae** [comment]
Hi @lakshmi-kannan, you can access the 5.2.1 (master branch) galaxy playbook here:

https://galaxy.ansible.com/sadsfae/ansible-elk/

**Comment by sadsfae** [comment]
I've also made a separate repo for the 2.4 series here:

https://galaxy.ansible.com/sadsfae/ansible-elk-2.4/

**Comment by lakshmi-kannan** [comment]
Thank you!
