### ISSUE TITLE
Consider supporting JournalBeat

### ISSUE THREAD

**Issue by portante** [sadsfae/ansible-elk#22]
See https://github.com/mheese/journalbeat.

**Comment by sadsfae** [comment]
Thanks for filing this @portante looks useful and I will work on adding it.

**Comment by sadsfae** [comment]
@portante got a chance to look at this again, it seems shipping go libs/binaries isn't too ideal but I found a maintained COPR repo here:

https://copr.fedorainfracloud.org/coprs/bcdonadio/journalbeat/

I've got this working but still need a valid ```journalbeat.template.json``` to ship, according to an issue filed recently that's still in the works will wait on that to be available from the author first unless you have one you can share that is shippable I'm happing including that and moving forward.

https://github.com/mheese/journalbeat/issues/47

**Comment by sadsfae** [comment]
I'm closing this for now, the dependent issue on journalbeat is still not resolved to proceed with implementing this here.  When it is I'll happily look at it again.
