### ISSUE TITLE
Please include X-Pack

### ISSUE THREAD

**Issue by ranjeetranjan** [sadsfae/ansible-elk#24]
Please include X-Pack too in this ELK

**Comment by sadsfae** [comment]
Hello @ranjeetranjan I've got a patch to add support for installing X-Pack for you.

You'll need to set these settings in ```install/group_vars/all.yml``` for the x-packs you want installed.
```
install_elasticsearch_xpack: true
install_kibana_xpack: true
install_logstash_xpack: true
```
