### ISSUE TITLE
Getting error on client getsockopt: connection refused

### ISSUE THREAD

**Issue by ranjeetranjan** [sadsfae/ansible-elk#25]
@sadsfae 

ERR Connecting error publishing events (retrying): dial tcp host:5044: getsockopt: connection refused

**Comment by sadsfae** [comment]
@ranjeetranjan this would occur if you don't have TCP/5044 open and listening on your ELK/EFK host, check that it's open to the world and listening via ```netstat -antp | grep 5044```

One issue I have seen with 5.x series is that logstash is very heavy on resources, my testing ELK/EFK VM has 8G memory and 4vcpu (updated requirements in README).

You might ensure your ELK/EFK has the resources needed for the 5.x version or try the 2.4 branch which is much less demanding.

**Comment by sadsfae** [comment]
@ranjeetranjan I've put in a TCP check for TCP/5044 for logstash for good measure here, this should help.
