### ISSUE TITLE
Add MetricBeat, Packetbeat, Topbeat to elk-client installation

### ISSUE THREAD

**Issue by knechtionscoding** [sadsfae/ansible-elk#36]
I needed to be able to install MetricBeat, PacketBeat, TopBeat and the other beats offered by Elasticsearch and so I added those in a scalable way, would you like a PR for those? Or do you not want to support those?

I moved the repo installation for the client into a dependency role called elk_client so that the elasticsearch.co repo is installed no matter the beat you specify and then it adds the correct config based on the beat you selected. I haven't had a chance to variablize beat selection yet, so that would be the next step.

**Comment by sadsfae** [comment]
Hey @KnechtionsCoding I'm happy including support for these but I want to keep the same structure of elk / elk-client as close as possible.  I'd prefer to enable and disable things in vars and then jinja2  and var check around them like what's done for the X-Pack stuff:

https://github.com/sadsfae/ansible-elk/blob/master/install/group_vars/all.yml#L63

Happy with any PR you want to work on here and we can discuss further.  Thanks man.

**Comment by knechtionscoding** [comment]
@sadsfae Not a problem, I'll rewrite them to those standards then and submit a new PR for it.

**Comment by knechtionscoding** [comment]
@sadsfae Just submitted the updated PR to you. Take a look and see if that's more inline with what you want.

**Comment by sadsfae** [comment]
This is resolved in:

https://github.com/sadsfae/ansible-elk/pull/41
