### ISSUE TITLE
ElasticSearch 5.5 not updating to 5.6

### ISSUE THREAD

**Issue by knechtionscoding** [sadsfae/ansible-elk#43]
There appears to be an issue with the repo that isn't updating elasitcsearch, even though it is updating the Kibana version. Currently kibana is on 5.6 and elasticsearch is on 5.5.2.

Potential solution is to remove the repo file, and use geturl to download the RPM and install based on a variable elk_version.

Thoughts @sadsfae ?

**Comment by knechtionscoding** [comment]
This would look something like this instead:

`- name: Install Logstash RPM
    yum:
        name: https://artifacts.elastic.co/downloads/logstash/logstash-{{ elk_version }}.rpm
        state: present
`

**Comment by sadsfae** [comment]
Hey @KnechtionsCoding, are we sure that it's just not a matter of Elastic being behind on their repo?  Yes that would work as well but I'd prefer to first see if it's just a temporary problem (doesn't seem to affect deployment via Ansible) instead of using ```get_url``` as a workaround (Elastic recommends repo installation for EL).

**Comment by knechtionscoding** [comment]
So the reason it came up was because I tried running a deployment and it picked up the 5.6 version of Kibana but not Elasticsearch. I'd assume that Elastic would update both.

We can wait and see if this is a temporary issue, I just wanted to let you know because I ran into the problem yesterday.

**Comment by sadsfae** [comment]
@KnechtionsCoding I'm traveling internationally so my responses here are hit and miss.  Good catch on this, let's see what happens.  I'll fire off another local VM set of tests this week to see if it "fixes" itself.

**Comment by knechtionscoding** [comment]
@sadsfae Not a problem, I'm just trying to contribute back upstream what I'm improving for the company so it's useful to others. I'll run a set later this week.

**Comment by sadsfae** [comment]
@KnechtionsCoding looks like this fixed itself upstream, as of a playbook run just now it reports ```elasticsearch-5.6.3-1.noarch``` on CentOS7.
