### ISSUE TITLE
Need to add import of dashboards and such for each beat

### ISSUE THREAD

**Issue by knechtionscoding** [sadsfae/ansible-elk#47]
I didn't add the import of dashboards for each beat. That needs to be added. Should be as simple as reusing the import code you have for Filebeat.

**Comment by alnash28** [comment]
I thought the reuse code was suffient

``` python 
- name: Configure kibana filebeat dashboards
  shell: sh /tmp/beats-dashboards-master/load.sh -url "http://localhost:9200" -user "{{kibana_user}}:{{kibana_password}}"
  ignore_errors: true
  tags: kibana
```
However does this assume prior knowledge of [How to Configure Flilebeat Dashboards?](https://www.elastic.co/guide/en/beats/filebeat/master/configuration-dashboards.html)

**Comment by knechtionscoding** [comment]
@anash28 Sorry, I added this to import the new beats that I added support for. This includes, heartbeat, packetbeat, metricbeat. The beats-dashboard-master doesn't include those because it was built for the filebeat only beat. So, we really need to add the new zip file, and then test the import. That's it. I just haven't had a chance because I've been busy the last two weeks.

**Comment by sadsfae** [comment]
@KnechtionsCoding I don't think this is an issue anymore as of `6.x` because dashboards are uploaded via the Kibana API.  Probably this can be closed?

**Comment by knechtionscoding** [comment]
Absolutely!
