### ISSUE TITLE
Order of Operations - Cert Generation

### ISSUE THREAD

**Issue by knechtionscoding** [sadsfae/ansible-elk#51]
@sadsfae Is there a reason for the cert generation to take place in the kibana role rather than the logstash role? I moved it to the logstash role in my own working copy, so that each role could be logically separate, but if there was a technical reason for it I'd love to know.

**Comment by sadsfae** [comment]
@KnechtionsCoding I placed most of the ancillary meta functionality inside Kibana as it's one of the last roles to fire off.  Sometimes it took a while for LS to fully instantiate on lower-spec machines so this was more of an ordering hack than anything else.  I think it's probably safe to move things into the areas they are more related to as needed as there are now proper checks and timeouts/waits for things to become available.

**Comment by knechtionscoding** [comment]
Okay, awesome. I've started moving those out, but I'll keep looking at it.

**Comment by alnash28** [comment]
@KnechtionsCoding @sadsfae I have started moving this out due to the potential need of running ELK on an m4.large OR m4.xlarge EC2 instance within AWS. Any pointers?

**Comment by knechtionscoding** [comment]
@anash28 If you'd like some pointers, feel free to open a new issue and I'll respond there, this one should be limited to the order of operations conversation.

**Comment by alnash28** [comment]
Understood. Thank You
