### ISSUE TITLE
I’d like to get in touch with you

### ISSUE THREAD

**Issue by CatherineMadden** [sadsfae/ansible-elk#52]
Hi Will,

I would like to say thank you for being involved in Open Source and discuss something regarding the UXDX conference which takes place in the RDS on October 5th.

Could you please send me your email address or drop me a message at catherine@uxdxconf.com?

Thanks in advance,
Catherine

**Comment by sadsfae** [comment]
Hi @CatherineMadden you can contact me directly at https://hobo.house.  I'll be out of the country during this timeframe but thanks for reaching out.
