### ISSUE TITLE
When Installing Packetbeat LIBPCAP is required

### ISSUE THREAD

**Issue by knechtionscoding** [sadsfae/ansible-elk#53]
When Packetbeat is selected for installation libpcap should be installed. Currently it isn't. Will add PR to support RHEL/CENTOS and Deb based systems.

**Comment by knechtionscoding** [comment]
I don't have a clean version to do a PR for. So I'll add the ansible here for you:


`- name: Install libpcap for packetbeat use (Centos)
  yum:
    name: libpcap
    state: present
  become: true
  when:
    - ansible_distribution == 'CentOS'
    - (ansible_distribution_major_version == "6") or (ansible_distribution_major_version == "7")

- name: Install libpcap for packetbeat use (Debian)
  apt:
    name: libpcap0.8
    state: present
  become: true
  when:
    - (ansible_distribution == 'Debian') or (ansible_distribution == 'Ubuntu')
`

That needs to be added to the main task of packetbeat

**Comment by sadsfae** [comment]
If ```libpcap``` is needed then the packetbeat RPM .spec should properly include it as a package dependency.  I'm not against adding it however.
