### ISSUE TITLE
Filebeat: Can someone point me in the right direction for understanding Filebeats functionality a little better

### ISSUE THREAD

**Issue by alnash28** [sadsfae/ansible-elk#55]
Hello @sadsfae @KnechtionsCoding 

I have been tinkering with this project for a few days. However, I dont have a decent understanding of the usage of filebeat [here](https://github.com/sadsfae/ansible-elk/blob/master/install/roles/filebeat/tasks/main.yml). Can you provide further documentation for LearnOps?

Thank you

**Comment by knechtionscoding** [comment]
@anash28 

Filebeat is a program installed on a client computer that reads from a file and ships logs to your logstash instance. It's configured via a YAML file and can read any log file you throw at it. More reading here: https://www.elastic.co/products/beats/filebeat
