### ISSUE TITLE
logstash ports on kibana role are FIXED and not using group_vars/all.yml

### ISSUE THREAD

**Issue by acomisario** [sadsfae/ansible-elk#57]
yes, file install/roles/kibana/tasks/main.yml

uses port 5000 and 5044 istead of using 

logstash_syslog_port
logstash_localsyslog_port

from group_vars/all.yml

**Comment by knechtionscoding** [comment]
@acomisario I just fixed that for you.

**Comment by acomisario** [comment]
Thank you!
question, how can i contribute ? doing pull requests does work ? i mean ... do they get reviewed ?
bes.t

**Comment by knechtionscoding** [comment]
@acomisario Yes. @sadsfae is out of the country right now so he hasn't had a chance to review any right now. Feel free to contribute through pull requests. If you have questions let me know and I'll do my best to answer them.

**Comment by sadsfae** [comment]
@KnechtionsCoding @acomisario thanks for filing this, I'm back from some extensive traveling now.  One thing I want to do is rebase the firewall stuff into it's own optional role.

Reviewing the PR for this now.

**Comment by sadsfae** [comment]
This is resolved now.
