### ISSUE TITLE
Issue with IP address in subjectAltName in /etc/pki/tls/openssl.cnf on CentOS

### ISSUE THREAD

**Issue by gmarziou** [sadsfae/ansible-elk#60]
Hello,

On CentOS 7, when subjectAltName contains an IP address it must uses `IP:` prefix otherwise openssl fails with this error:

~~~~
Error Loading extension section v3_ca
140585944606624:error:2207507C:X509 V3 routines:v2i_GENERAL_NAME_ex:missing value:v3_alt.c:531:
140585944606624:error:22098080:X509 V3 routines:X509V3_EXT_nconf:error in extension:v3_conf.c:95:name=subjectAltName, value=10.0.2.15
~~~~

To make it work, value in  `/etc/pki/tls/openssl.cnf` should be like below:

~~~
subjectAltName = "IP: 10.0.2.15"
~~~

It impacts 2 roles [fluentd](https://github.com/sadsfae/ansible-elk/blob/master/install/roles/fluentd/tasks/main.yml#L59) and [logstash](https://github.com/sadsfae/ansible-elk/blob/master/install/roles/logstash/tasks/main.yml#L51).

~~~~
openssl version
OpenSSL 1.0.2k-fips  26 Jan 2017
~~~~

~~~~
cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core)
~~~~

**Comment by sadsfae** [comment]
Thanks for filing this @gmarziou let me test this and submit a patch.

**Comment by gmarziou** [comment]
Thanks
