### ISSUE TITLE
ELK-server not found

### ISSUE THREAD

**Issue by mrafieee** [sadsfae/ansible-elk#62]
FAILED! => {"failed": true, "msg": "The task includes an option with an undefined variable. The error was: 'elk_server' is undefined\n\nThe error appears to have been in '/vagrant/ansible-host/roles/elk_client/tasks/main.yml': line 30, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Install ELK server SSL client certificate\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'elk_server' is undefined"}

**Comment by knechtionscoding** [comment]
Hi @mrafieee 

Per the Read Me you need to run the elk_client command as follows: ansible-playbook -i hosts install/elk-client.yml --extra-vars 'elk_server=X.X.X.X' That will define the variable in question. Without that definition you cannot install the beats. Can you share the command you ran?

**Comment by mrafieee** [comment]
passed it through all.yml and it is passing now thanks for the quick response
