### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by MrMEEE** [sadsfae/ansible-elk#67]
Hi

I tried running your playbook against a minimal install RHEL7, enabling Fluentd.... and it fails because it can't build the elasticsearch fluentd plugin gem... 

gcc and make was missing.. after installing these packages everything seems to work...

**Comment by MrMEEE** [comment]
After some more investigation, only gcc is needed... make is already there..

**Comment by sadsfae** [comment]
Thanks for reporting this, fix coming shortly.
