### ISSUE TITLE
The conditional check '(es_curator_tool == 'install')' failed

### ISSUE THREAD

**Issue by shuneguchi** [sadsfae/ansible-elk#7]
The playbook fails with the following error since the parameter of "es_curator_tool" is not specified in group_vars by default.

``` yml
TASK [curator : Copy curator yum repo file] ************************************
fatal: [192.168.43.70]: FAILED! => {"failed": true, "msg": "The conditional check '(es_curator_tool == 'install')' failed. The error was: error while evaluating conditional ((es_curator_tool == 'install')): 'es_curator_tool' is undefined"}
```

Adding such parameter in group_vars/all.yml workaround the problem.

Please advise.

**Comment by sadsfae** [comment]
Hi @ShunEguchi thanks for reporting this, it's fixed now - looks like I didn't update the `elk.yml` to use the new conditional check which was put in place recently.

https://github.com/sadsfae/ansible-elk/commit/6f00f6b003fdd8fcb5aeab68f85680c73463c909

**Comment by shuneguchi** [comment]
Thanks for your prompt response! Plus, thanks for sharing this wonderful playbook. It totally worked!!
