### ISSUE TITLE
Installed version of Curator does not match configuration

### ISSUE THREAD

**Issue by crossan007** [sadsfae/ansible-elk#71]
The Curator repo file installs version 3: https://github.com/sadsfae/ansible-elk/blob/master/install/roles/curator/files/curator.repo

Curator version 3 does not have a `--config` cli parameter. This parameter is referenced in the cron job.

Likely, Curator version 5 should be installed:
https://www.elastic.co/guide/en/elasticsearch/client/curator/current/yum-repository.html

**Comment by sadsfae** [comment]
Thanks for filing this, I've corrected the repo.  `--config` still seems to work via:

```
curator --config /etc/elasticsearch/curator-config.yml /etc/elasticsearch/curator-action.yml
```

**Comment by sadsfae** [comment]
Please re-open if this is an issue, it works for me.  Thank you.
