### ISSUE TITLE
TASK [logstash : Load filebeat JSON index template]

### ISSUE THREAD

**Issue by gitmkc** [sadsfae/ansible-elk#73]
I am getting below error in logstash.
fatal: [elkserver]: FAILED! => {"attempts": 30, "changed": false, "content": "", "msg": "Status code was -1 and not [200]: Request failed: <urlopen error [Errno 111] Connection refused>", "redirected": false, "status": -1, "url": "http://localhost:9200/_template/filebeat?pretty"}

**Comment by sadsfae** [comment]
Hey @gitmkc I'm not able to reproduce this, the specific Playbook line that runs this is:

https://github.com/sadsfae/ansible-elk/blob/master/install/roles/logstash/tasks/main.yml#L76

It works fine for me:

```
TASK [logstash : Load filebeat JSON index template] ***********************************************************************************************
ok: [host-01]
```

Typically this will fail if Elasticsearch isn't up and running yet, this can take some time on slower systems which is why we have 30 attempts.  What kind of resources does your ELK host have?  I have only seen this when it's not powerful enough (memory, cpu) to instantiate all the Elastic Java processes beforehand.

We try to stagger out dependent service deployment in this playbook to accommodate as well as build in sensible timeouts (which is why you see a lot of non-Kibana stuff happen in the Kibana role).

**Comment by derekslenk** [comment]
I can reproduce this error. While installing fluentd with rsyslog, this error happens:

```
TASK [fluentd : Install fluentd elasticsearch plugin] ****************************************************************************
changed: [elk-centos.lan]

TASK [fluentd : Install fluentd beats plugin] ************************************************************************************
changed: [elk-centos.lan]

TASK [fluentd : Load filebeat JSON index template] *******************************************************************************fatal: [elk-centos.lan]: 
FAILED! => {"changed": false, "content": "{\n  \"error\" : {\n    \"root_cause\" : [\n      {\n        \"type\" : \"mapper_parsing_exception\",\n        \"reason\" : \"No handler for type [string] declared on field [message]\"\n      }\n    ],\n    \"type\" : \"mapper_parsing_exception\",\n    \"reason\" : \"Failed to parse mapping [_default_]: No handler for type [string] declared on field [message]\",\n    \"caused_by\" : {\n      \"type\" : \"mapper_parsing_exception\",\n      \"reason\" : \"No handler for type [string] declared on field [message]\"\n    }\n  },\n  \"status\" : 400\n}\n", "content_length": "505", "content_type": "application/json; charset=UTF-8", "json": {"error": {"caused_by": {"reason": "No handler for type [string] declared on field [message]", "type": "mapper_parsing_exception"}, "reason": "Failed to parse mapping [_default_]: No handler for type [string] declared on field [message]", "root_cause": [{"reason": "No handler for type [string] declared on field [message]", "type": "mapper_parsing_exception"}], "type": "mapper_parsing_exception"}, "status": 400}, "msg": "Status code was 400 and not [200]: HTTP Error 400: Bad Request", "redirected": false, "status": 400, "url": "http://localhost:9200/_template/filebeat?pretty", "warning": "299 Elasticsearch-6.6.1-1fd8f69 \"Deprecated field [template] used, replaced by [index_patterns]\" \"Mon, 11 Mar 2019 21:37:19 GMT\""}
...ignoring

TASK [fluentd : Start fluentd service] *******************************************************************************************
changed: [elk-centos.lan]
```

**Comment by sadsfae** [comment]
It's been a while since I've tested the full EFK deployment on CentOS, looks like you also have what could be a fluentd-related issue here too:  https://github.com/sadsfae/ansible-elk/issues/76

If this is still occurring I'll probably notice it when testing out issue #76 also.
