### ISSUE TITLE
Couldn't find any Elasticsearch data

### ISSUE THREAD

**Issue by kcxg** [sadsfae/ansible-elk#74]
when i start kibana and looking in management tab it is displaying message :
"Couldn't find any Elasticsearch data
You'll need to index some data into Elasticsearch before you can create an index pattern "

**Comment by sadsfae** [comment]
> when i start kibana and looking in management tab it is displaying message :
> "Couldn't find any Elasticsearch data
> You'll need to index some data into Elasticsearch before you can create an index pattern "

Hi @kcxg are you following the post-setup steps to create an index pattern first before hand?

https://github.com/sadsfae/ansible-elk/#create-your-kibana-index-pattern

If so what does this report from your ELK node?

```
curl -GET http://localhost:9200/_cat/indices
```

**Comment by kcxg** [comment]
I  followed the post-setup steps to create an index pattern first before hand


`$curl -GET http://localhost:9200/_cat/indices

green open .kibana_1 n7-42WjmTfyZn5uHvH0qoA 1 0 174 9 260.3kb 260.3kb
`

**Comment by sadsfae** [comment]
> I followed the post-setup steps to create an index pattern first before hand
> 
> `$curl -GET http://localhost:9200/_cat/indices
> 
> green open .kibana_1 n7-42WjmTfyZn5uHvH0qoA 1 0 174 9 260.3kb 260.3kb
> `

Ok, that looks good.  When you created the Index pattern you should be using `logstash-*` as the name for logstash to properly send data, I don't see that there - can you try creating that under **management** --> **Kibana Index Patterns**

Mine looks like this after adding a `logstash-*` pattern, clicking next, selecting `@timestamp` and create index.

![screenshot_2018-12-07_15-59-24](https://user-images.githubusercontent.com/3940978/49658163-528f4100-fa39-11e8-9d07-aad3526478d0.png)


```
# curl -GET http://localhost:9200/_cat/indices
yellow open logstash-2018.12.07 Rrf7uT0lSh6MtCWOcvyO3Q 5 1 242 0 754.2kb 754.2kb
green  open .kibana_1           nVuii57WRPGz-Qx69QR6KA 1 0   4 0  23.1kb  23.1
```

**Comment by kcxg** [comment]
I add  a  logstash-* pattern but  cant  click next
![image](https://user-images.githubusercontent.com/31840413/49659145-7f197c00-fa7e-11e8-9760-c7a2dd347e08.png)

I installed it twice and had the same problem.

**Comment by kcxg** [comment]
> I add a logstash-* pattern but cant click next
> ![image](https://user-images.githubusercontent.com/31840413/49659145-7f197c00-fa7e-11e8-9760-c7a2dd347e08.png)
> 
> I installed it twice and had the same problem.


I just went to the bathroom, and after I came back,  one is  succeeded. Thank you  very much!

**Comment by sadsfae** [comment]
> > I add a logstash-* pattern but cant click next
> > ![image](https://user-images.githubusercontent.com/31840413/49659145-7f197c00-fa7e-11e8-9760-c7a2dd347e08.png)
> > I installed it twice and had the same problem.
> 
> I just went to the bathroom, and after I came back, one is succeeded. Thank you very much!

Hey, cool!  Sometimes it takes a while on lower-end systems or low cpu/memory for it all to instantiate.  Are you sorted now?

Yeah, the logstash portions of the playbook need to create the logstash-* index (based on using rsyslog method of sending the ELK system logs itself to ELK to create them).

**Comment by sadsfae** [comment]
Closing this out now, re-open if you still have a problem.
