### ISSUE TITLE
Default install doesn't work on CentOS 7.6

### ISSUE THREAD

**Issue by derekslenk** [sadsfae/ansible-elk#76]
Followed the install instructions, but when going to kibana to try and make an index pattern, it is not finding any logstash sources. I only installed the server but in your instructions it looks like I should see some data from the local server.

Any help would be appreciated.

[root@elk-centos ~]# cat /etc/centos-release
CentOS Linux release 7.6.1810 (Core)

**Comment by somabc** [comment]
I just carried out a CentOS 7.6.1810 install and logstash shows up immediately.

Are you sending data to the host?

If you go to install/group/vars/all.yml

and modify

#Install Metricbeat
install_metricbeat: true
#This should be installed on only one server in your environment.
#Install Heartbeat
install_heartbeat: true

You will be sending data from your host into elasticsearch.

**Comment by derekslenk** [comment]
I have tried enabling heartbeat and metricbeat, and still it looks like nothing is being logged from the localhost.

I am going to try removing curator and if that doesn't work. I will just create my VM again I guess

**Comment by derekslenk** [comment]
Here are the groupvars I had set:
```
---

# Default Ansible user
# change this if you use a non-root user for running Ansible playbooks
ansible_system_user: root

# EPEL Repository for extra packages
epel_repo: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm


manage_firewall: true


nginx_kibana_port: 80

elk_server_ssl_cert_port: 8080
#
# Kibana options
# change this to affect nginx-wrapped htpasswd authentication
kibana_user: admin
kibana_password: admin


logging_backend: logstash
#
### logstash options ###
logstash_syslog_port: 5044
logstash_localsyslog_port: 5000
### rsyslog options
# set this to true if you want to accept
# external syslog traffic
syslog_listen_external: true 
### fluentd options ###
fluentd_syslog_port: 42185
fluentd_http_port: 9919
fluentd_debug_port: 24230

es_local_port: 9200
es_listen_external: false
### install curator tool ###
# curator is the recommended tool for managing elasticsearch indexes
# https://www.elastic.co/guide/en/elasticsearch/client/curator/current/index.html
# default is no (set to blank) or false
# set the below variable to 'true' to activate
install_curator_tool: false

xpack_elastic_user_password: changeme
# install elastic x-pack
install_elasticsearch_xpack: false
# install kibana x-pack
install_kibana_xpack: false
# install logstash x-pack
install_logstash_xpack: false

#Install Metricbeat
install_metricbeat: true
#Install Packetbeat
install_packetbeat: true

#This should be installed on only one server in your environment.
#Install Heartbeat
install_heartbeat: true

```

**Comment by somabc** [comment]
That looks good.

You don't need to specify logging_backend: logstash  as it will assume logstash but there is no harm including it. The only other thing I can see is you have syslog turned on for logstash. As a test I would try having this as false. syslog_listen_external: false 

Then install again and check logstash is listening on port 5044 after the install with sudo netstat -tuplen| grep logstash and systemctl status logstash -l

**Comment by derekslenk** [comment]
I am doing a fresh install/fresh checkout - only changing the hosts and packetbeat,metricbeat,and heartbeat. Still no luck.

It does work if I install the client locally to itself. Is that assumed that I am installing the client to the same server as the host?

**Comment by sadsfae** [comment]
> I am doing a fresh install/fresh checkout - only changing the hosts and packetbeat,metricbeat,and heartbeat. Still no luck.
> 
> It does work if I install the client locally to itself. Is that assumed that I am installing the client to the same server as the host?

Logstash can sometimes take a while to startup but your initial seed of system logs should come from the Elastic host itself (via local rsyslog)

https://github.com/sadsfae/ansible-elk/blob/master/install/roles/kibana/tasks/main.yml#L189

This is **not done** when using fluentd for the local Elastic host (as we'd expect fluentd to populate this instead).  It's been a while since I've tested a full EFK deployment on EL and frankly most people don't use this setup and opt for ELK instead with Logstash accepting data from hosts (and via syslog on localhost of Elastic node as well).

I've been quite busy and doing some extended travel lately but thank you @somabc for the help here.  When I can find some time let me try a fresh EL76 / EFK deployment and see if I can replicate this.

**EDIT**

I see above that you're using logstash and not fluentd, this should all work as-is, strange it doesn't.  I will test out a fresh EL7.6 deployment to see if I can get a failure.

**Comment by sadsfae** [comment]
Update here, I found some time and tried a fresh deployment on the latest CentOS7 and noticed there are some issue with the following things enabled:

```
install_metricbeat: true
install_packetbeat: true
install_heartbeat: true
```

This has now been fixed here:

https://github.com/sadsfae/ansible-elk/issues/79
https://github.com/sadsfae/ansible-elk/commit/d2bbfe4b16db299a536338eb082906cc88b86827

Things work fine for me now with the same options you have above, give it another try and see if you still have issues.
