### ISSUE TITLE
Use Apache for Reverse Proxy to support LDAP auth

### ISSUE THREAD

**Issue by crossan007** [sadsfae/ansible-elk#77]
Apache provides better(?) support for LDAP authentication, and also provides a pass-through proxy mode.  I couldn't seem to get the NGINX LDAP auth to work (additional compiled, possibly non-free, modules were required)

Would you welcome a pull request adding an optional Apache role instead of NGINX?

I'm currently running Apache with LDAP against an on-site Active Directory for proxying Kibana dashboards.

**Comment by sadsfae** [comment]
Hey @crossan007 that's a great idea, thanks for filing this.  Apache is indeed a better choice when relying on having more reverse proxy functionality as it has so many more modules for this.

I can work on adding this but a PR is also happily accepted.

**Comment by crossan007** [comment]
I'll make a PR sometime next week.  

I'm using a fork of this repo with Apache and ldap auth in production :-) 

I should be able to cherry pick the relevant bits to a branch here.

**Comment by sadsfae** [comment]
> I'll make a PR sometime next week.
> 
> I'm using a fork of this repo with Apache and ldap auth in production :-)
> 
> I should be able to cherry pick the relevant bits to a branch here.

Hey, that's awesome.  I would normally do this via https://github.com/sadsfae/ansible-elk/blob/master/install/group_vars/all.yml variable and leaving nginx the default.

From there you can use the `when` conditional in the playbook like:

https://github.com/sadsfae/ansible-elk/blob/master/install/elk.yml#L17

Looking forward to the PR, if you get really busy I'm happy to knock it out also - much appreciated.

**Comment by sadsfae** [comment]
@crossan007 I've got all the changes for this working except for the Apache vhost / ProxyPass stuff.  Do you have an example you can share?

**Comment by sadsfae** [comment]
> @crossan007 I've got all the changes for this working except for the Apache vhost / ProxyPass stuff. Do you have an example you can share?

Nevermind, I got it working - patch coming soon.
