### ISSUE TITLE
a question from fish

### ISSUE THREAD

**Issue by zhihaogitup** [sadsfae/ansible-elk#81]
I have a problem, this problem happened in "Enable logstash service", I can not find the relevant information, I wonder if you can help me answer，log：“Could not find the requested service logstash: host”

**Comment by sadsfae** [comment]
Hi @zhihaogitup can you run the playbook via `ansible-playbook -vvv` and [paste the run logs to pastebin](https://paste.fedoraproject.org/)?  That will help us better understand what the problem is.

**Comment by harrytruman** [comment]
Huh. I'm hitting the same thing on an unrelated project. It's not an Ansible problem, I don't believe. I'm installing the latest Logstash 7.4, and I've tried the packages from both the yum repo and by downloading/installing manually. Same thing:
```
{"changed": false, "msg": "Could not find the requested service logstash: host"}

# systemctl start logstash
Failed to start logstash.service: Unit logstash.service not found.
```

**Comment by sadsfae** [comment]
> Huh. I'm hitting the same thing on an unrelated project. It's not an Ansible problem, I don't believe. I'm installing the latest Logstash 7.4, and I've tried the packages from both the yum repo and by downloading/installing manually. Same thing:
> 
> ```
> {"changed": false, "msg": "Could not find the requested service logstash: host"}
> 
> # systemctl start logstash
> Failed to start logstash.service: Unit logstash.service not found.
> ```

Occasionally the upstream packaging breaks, this wouldn't be the first time.  I'll try a fresh deployment and report back when I find some time.

**Comment by harrytruman** [comment]
@sadsfae A fresh deploy solved the problem. If not, this certainly will...

```/usr/share/logstash/bin/system-install /etc/logstash/startup.options systemd```

**Comment by sadsfae** [comment]
I just did a full, fresh deployment on CentOS7 today and had no issues either, closing this out.
