### ISSUE TITLE
Import ElasticSearch GPG Key fails on elk client role

### ISSUE THREAD

**Issue by japplewhite** [sadsfae/ansible-elk#97]
**Your System Details** 

**Describe the bug**
When the elk client role runs it fails on installing the GPG key for elastisearch
Making the following change fixed the issue
 #rpm_key: key=http://packages.elastic.co/GPG-KEY-elasticsearch
  rpm_key: key=https://artifacts.elastic.co/GPG-KEY-elasticsearch

**Comment by sadsfae** [comment]
Thanks for filing this @japplewhite.  These seem like they same files and are both accessible, wonder if there's a benefit to one or the other.  It's been a while but I'll experiment with this and see if it's still a problem.

**Comment by sadsfae** [comment]
Closing this, I'm unable to reproduce it.
